start:
	g++  ./*.cpp  ./ipfs/*.cpp  ./dataSource/*.cpp  ./cloudComputing/*.cpp  -o dataCapitalization -g \
	-I ../libraries/HElib/src/ \
	-L ../libraries/HElib/src/  -lfhe -lntl -lsqlite3 -lgmp -ljsoncpp -lcurl  -std=c++11
